version: '2'
services:
    jhdocker-app:
        image: jhdocker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhdocker-postgresql:5432/jhdocker_prod
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhdocker-postgresql:
        extends:
            file: postgresql.yml
            service: jhdocker-postgresql
