version: '2'
services:
    jhdocker-postgresql:
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/jhdocker/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        ports:
            - "5433:5432"
